### ISSUE TITLE
fix: make all services support ARM architecture

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi_stack#52]
As a Mac user postgraphile doesn't start because there is an "unsupported platform" error. Images that need updates are:

- [x] ~dargmuesli/jobber-aws-msmtp~ 🟩
- [x] dargmuesli/pg-amqp-bridge 🟩
- [x] graphile/postgraphile 🟥 https://github.com/graphile/postgraphile/pull/1681
- [x] tusproject/tusd 🟨 https://github.com/tus/tusd/pull/848

🟩 = low priority, 🟨 = medium priority, 🟥 = high priority

**Comment by dargmuesli** [comment]
I've added a list of images that require an update along with pull requests that implement the necessary changes.

**Comment by dargmuesli** [comment]
@PatrickMi `postgraphile` should now start on macOS successfully as a stack service. Could you verify that? :)
