### ISSUE TITLE
feat(auth): add a traefik plugin for authentication of form captchas

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi_stack#72]
When submitting a form turnstile will be used to authenticate the user as a real user and no bot. A key, that was generated by turnstile will be sent with the request. To check this, a traefik plugin has to be created to forward all requests to the nuxt server auth-proxy api which checks if a turnstile check is needed and if it is, checks if the provided key is valid.

**Comment by dargmuesli** [comment]
Please always give a precise description of what's needed to be done and why when creating issues :pray:

**Comment by PatrickMi** [comment]
PR to this issue: https://github.com/maevsi/maevsi_stack/pull/73

**Comment by dargmuesli** [comment]
If you write "Resolves #72" in the PR's description, it would link the PR to this issue and close it once merged.

**Comment by PatrickMi** [comment]
> If you write "Resolves #72" in the PR's description, it would link the PR to this issue and close it once merged.

Good point. I'll do it next time 👍
